### PR TITLE
Expose current version as a constant

### PR DESCRIPTION
**Pull request by jonahwilliams**
Required so that customer:money can do a runtime lookup of the correct version for network assets.

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
Can we instead make this the git hash?

**Comment by jonahwilliams** [comment]
But that would imply they'd need to rev the version everytime we change the encoding? But that isn't true, we haven't broken compatibility besides the single change to path encoding.

**Comment by dnfield** [comment]
I think that if we don't rev the version every time we make a new commit, we will definitely forget to rev the version when we do break it.

I was hoping that however customer: money handled this, it would be more on their end (e.g. reading the METADATA file to get the origin commit and using that).

**Comment by jonahwilliams** [comment]
Do we actually have any changes planned beyond images?

**Comment by jonahwilliams** [comment]
(because I was sort of assuming we were almost feature complete)

**Comment by jonahwilliams** [comment]
discussed offline, these don't need to match

**Pull request closed without merging**
